name: Release

on:
    release:
        types: [released]

jobs:
  release:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification 📯
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Version ${{ steps.semantic.outputs.new_release_version }} of the {{ github.event.repository.name }} has been released.'
