name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: 180
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 180 days with no activity. Feel free to unstale it at any time by adding a comment."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale. Feel free to reopen it at any time, if this issue is still relevant."
          exempt-issue-labels: "permanent"
          days-before-pr-stale: 365
          days-before-pr-close: 30
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 180 days with no activity. Feel free to unstale it at any time by adding a comment."
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as stale. Feel free to reopen it at any time, if you are still working on it."
          exempt-pr-labels: "permanent"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
